/*
  words.js — 每日英文單字的字庫檔案
  ============================================
  這裡是全部的單字資料，App 會從這裡挑字。

  【怎麼自己新增單字？】
  1. 找到最後面的 WORDS 陣列（一堆用 { } 包起來的物件，中間用逗號分隔）。
  2. 複製任何一筆（一整組 { ... }），貼在陣列最後一個 } 的後面，記得補上逗號。
  3. 照著格式填好你自己的內容：
     word       -> 英文單字或片語，例如 "eat"
     pos        -> 詞性，例如 "n."（名詞）"v."（動詞）"adj."（形容詞）
                   "adv."（副詞）"phr."（片語）
     zh         -> 中文意思
     level      -> 難度等級 "L1"~"L6"（數字越大越難），口語片語請寫 "口語"
     tag        -> 主題分類，例如 "飲食點餐"（跟現有的主題名稱一樣就會歸在一起）
     example    -> 一句英文例句，把該單字/片語前後加上兩個星號 ** 讓它變粗體
                   例如 "I like to **eat** breakfast."
     exampleZh  -> 例句的中文翻譯
  4. 存檔重新整理網頁就會生效了！
  5. 小提醒：每個 word 內容盡量不要重複，因為 App 會用它來記錄複習進度。
     另外，單字總數如果是 10 的倍數，每天顯示 10 個字會排得比較整齊，
     不過就算不是 10 的倍數，App 也能正常運作（只是輪到最後幾天可能不滿 10 個）。
*/

const WORDS = [
  // ===== 飲食點餐 Food =====
  { word: "eat", pos: "v.", zh: "吃", level: "L1", tag: "飲食點餐", example: "I always **eat** breakfast before school.", exampleZh: "我上學前總是吃早餐。" },
  { word: "drink", pos: "v.", zh: "喝", level: "L1", tag: "飲食點餐", example: "You should **drink** more water every day.", exampleZh: "你應該每天多喝水。" },
  { word: "menu", pos: "n.", zh: "菜單", level: "L1", tag: "飲食點餐", example: "Can I see the **menu**, please?", exampleZh: "可以給我看一下菜單嗎？" },
  { word: "order", pos: "v.", zh: "點餐", level: "L2", tag: "飲食點餐", example: "I'd like to **order** a cheeseburger and fries.", exampleZh: "我想點一個起司漢堡和薯條。" },
  { word: "delicious", pos: "adj.", zh: "好吃的", level: "L2", tag: "飲食點餐", example: "This soup smells **delicious**.", exampleZh: "這碗湯聞起來很好吃。" },
  { word: "hungry", pos: "adj.", zh: "飢餓的", level: "L1", tag: "飲食點餐", example: "I'm so **hungry** I could eat a whole pizza.", exampleZh: "我餓到可以吃下一整個披薩。" },
  { word: "thirsty", pos: "adj.", zh: "口渴的", level: "L1", tag: "飲食點餐", example: "After running, I felt really **thirsty**.", exampleZh: "跑步後我覺得非常口渴。" },
  { word: "restaurant", pos: "n.", zh: "餐廳", level: "L1", tag: "飲食點餐", example: "We had dinner at a new **restaurant** downtown.", exampleZh: "我們在市區一家新餐廳吃晚餐。" },
  { word: "waiter", pos: "n.", zh: "服務生", level: "L2", tag: "飲食點餐", example: "The **waiter** brought us extra napkins.", exampleZh: "服務生幫我們拿了額外的餐巾紙。" },
  { word: "bill", pos: "n.", zh: "帳單", level: "L2", tag: "飲食點餐", example: "Could you bring us the **bill**, please?", exampleZh: "可以幫我們拿帳單過來嗎？" },
  { word: "tip", pos: "n.", zh: "小費", level: "L2", tag: "飲食點餐", example: "We left a 10% **tip** for good service.", exampleZh: "因為服務很好，我們留了一成的小費。" },
  { word: "dessert", pos: "n.", zh: "甜點", level: "L2", tag: "飲食點餐", example: "I always save room for **dessert**.", exampleZh: "我總是會留肚子吃甜點。" },
  { word: "spicy", pos: "adj.", zh: "辣的", level: "L2", tag: "飲食點餐", example: "This curry is too **spicy** for me.", exampleZh: "這咖哩對我來說太辣了。" },
  { word: "sour", pos: "adj.", zh: "酸的", level: "L2", tag: "飲食點餐", example: "The lemon tea tastes a little **sour**.", exampleZh: "這杯檸檬茶喝起來有點酸。" },
  { word: "leftovers", pos: "n.", zh: "剩菜", level: "L4", tag: "飲食點餐", example: "We had the **leftovers** for lunch the next day.", exampleZh: "我們隔天午餐吃了剩菜。" },
  { word: "takeout", pos: "n.", zh: "外帶", level: "L3", tag: "飲食點餐", example: "Let's just order **takeout** tonight.", exampleZh: "我們今晚就叫外帶吧。" },
  { word: "reservation", pos: "n.", zh: "訂位", level: "L4", tag: "飲食點餐", example: "I made a **reservation** for two at seven.", exampleZh: "我訂了七點兩人的位子。" },
  { word: "ingredient", pos: "n.", zh: "食材", level: "L4", tag: "飲食點餐", example: "Fresh **ingredients** make the dish taste better.", exampleZh: "新鮮的食材讓這道菜更美味。" },
  { word: "recipe", pos: "n.", zh: "食譜", level: "L3", tag: "飲食點餐", example: "My mom shared her fried rice **recipe** with me.", exampleZh: "我媽媽跟我分享了她的炒飯食譜。" },
  { word: "appetite", pos: "n.", zh: "食慾", level: "L4", tag: "飲食點餐", example: "The hot weather gave me no **appetite**.", exampleZh: "炎熱的天氣讓我完全沒有食慾。" },
  { word: "beverage", pos: "n.", zh: "飲料", level: "L4", tag: "飲食點餐", example: "The cafe offers many kinds of **beverages**.", exampleZh: "這間咖啡廳提供很多種飲料。" },
  { word: "nutritious", pos: "adj.", zh: "營養的", level: "L5", tag: "飲食點餐", example: "Vegetables are **nutritious** and low in calories.", exampleZh: "蔬菜富含營養且低卡路里。" },
  { word: "grab a bite", pos: "phr.", zh: "隨便吃點東西", level: "口語", tag: "飲食點餐", example: "Let's **grab a bite** before the movie starts.", exampleZh: "電影開始前我們先隨便吃點東西吧。" },
  { word: "eat like a horse", pos: "phr.", zh: "吃很多、食量很大", level: "口語", tag: "飲食點餐", example: "My brother can **eat like a horse** after basketball practice.", exampleZh: "我弟弟打完籃球練習後食量很驚人。" },
  { word: "rip-off", pos: "n.", zh: "坑錢的東西", level: "口語", tag: "飲食點餐", example: "Five dollars for a small water bottle? That's a total **rip-off**!", exampleZh: "一小瓶水要五美元？根本是坑錢！" },
  { word: "dig in", pos: "phr.", zh: "開動吧", level: "口語", tag: "飲食點餐", example: "The food is ready, so **dig in**!", exampleZh: "食物準備好了，開動吧！" },
  { word: "utensils", pos: "n.", zh: "餐具", level: "L3", tag: "飲食點餐", example: "Please set the table with clean **utensils**.", exampleZh: "請用乾淨的餐具擺放餐桌。" },

  // ===== 購物消費 Shopping =====
  { word: "buy", pos: "v.", zh: "買", level: "L1", tag: "購物消費", example: "I want to **buy** a new pair of shoes.", exampleZh: "我想買一雙新鞋。" },
  { word: "sell", pos: "v.", zh: "賣", level: "L1", tag: "購物消費", example: "The store **sells** cheap school supplies.", exampleZh: "這間店賣便宜的文具。" },
  { word: "price", pos: "n.", zh: "價格", level: "L1", tag: "購物消費", example: "The **price** of this bag is too high.", exampleZh: "這個包包的價格太高了。" },
  { word: "cheap", pos: "adj.", zh: "便宜的", level: "L1", tag: "購物消費", example: "This night market sells really **cheap** snacks.", exampleZh: "這個夜市賣的小吃真的很便宜。" },
  { word: "expensive", pos: "adj.", zh: "昂貴的", level: "L1", tag: "購物消費", example: "That phone looks really **expensive**.", exampleZh: "那支手機看起來很貴。" },
  { word: "discount", pos: "n.", zh: "折扣", level: "L2", tag: "購物消費", example: "I got a 20% **discount** on these jeans.", exampleZh: "我這件牛仔褲拿到八折優惠。" },
  { word: "receipt", pos: "n.", zh: "收據", level: "L2", tag: "購物消費", example: "Don't forget to keep your **receipt**.", exampleZh: "別忘了留著你的收據。" },
  { word: "cash", pos: "n.", zh: "現金", level: "L1", tag: "購物消費", example: "Do you have any **cash** on you?", exampleZh: "你身上有現金嗎？" },
  { word: "credit card", pos: "n.", zh: "信用卡", level: "L2", tag: "購物消費", example: "I paid for the sneakers with my **credit card**.", exampleZh: "我用信用卡買了那雙球鞋。" },
  { word: "refund", pos: "n.", zh: "退款", level: "L3", tag: "購物消費", example: "The shirt didn't fit, so I asked for a **refund**.", exampleZh: "這件襯衫不合身，所以我要求退款。" },
  { word: "exchange", pos: "v.", zh: "換貨", level: "L3", tag: "購物消費", example: "Can I **exchange** this for a bigger size?", exampleZh: "我可以把這個換成大一點的尺寸嗎？" },
  { word: "sale", pos: "n.", zh: "特賣", level: "L2", tag: "購物消費", example: "The department store is having a big **sale** this weekend.", exampleZh: "這間百貨公司這週末有大特賣。" },
  { word: "bargain", pos: "n.", zh: "划算的交易", level: "L4", tag: "購物消費", example: "At that price, this jacket is a real **bargain**.", exampleZh: "以這個價格來說，這件外套真的很划算。" },
  { word: "customer", pos: "n.", zh: "顧客", level: "L2", tag: "購物消費", example: "The shop always treats its **customers** kindly.", exampleZh: "這間店總是很親切地對待顧客。" },
  { word: "size", pos: "n.", zh: "尺寸", level: "L1", tag: "購物消費", example: "Do you have this shirt in a smaller **size**?", exampleZh: "這件衣服有小一點的尺寸嗎？" },
  { word: "fitting room", pos: "n.", zh: "試衣間", level: "L2", tag: "購物消費", example: "You can try it on in the **fitting room** over there.", exampleZh: "你可以在那邊的試衣間試穿。" },
  { word: "brand", pos: "n.", zh: "品牌", level: "L3", tag: "購物消費", example: "She only buys clothes from her favorite **brand**.", exampleZh: "她只買她最喜歡品牌的衣服。" },
  { word: "quality", pos: "n.", zh: "品質", level: "L3", tag: "購物消費", example: "This backpack is cheap but the **quality** is great.", exampleZh: "這個背包很便宜但品質很好。" },
  { word: "checkout", pos: "n.", zh: "結帳", level: "L3", tag: "購物消費", example: "There was a long line at the **checkout** counter.", exampleZh: "結帳櫃檯排了很長的隊伍。" },
  { word: "installment", pos: "n.", zh: "分期付款", level: "L5", tag: "購物消費", example: "I'm paying for my laptop in monthly **installments**.", exampleZh: "我用每月分期付款來付我的筆電。" },
  { word: "budget", pos: "n.", zh: "預算", level: "L3", tag: "購物消費", example: "I need to stick to my **budget** this month.", exampleZh: "我這個月需要堅守我的預算。" },
  { word: "window shopping", pos: "phr.", zh: "只看不買地逛街", level: "口語", tag: "購物消費", example: "We went **window shopping** at the mall after school.", exampleZh: "放學後我們去購物中心只逛不買。" },
  { word: "splurge", pos: "v.", zh: "揮霍、狠狠花錢", level: "口語", tag: "購物消費", example: "I decided to **splurge** on new headphones.", exampleZh: "我決定豪爽地買下新耳機。" },
  { word: "a steal", pos: "n.", zh: "超划算的東西", level: "口語", tag: "購物消費", example: "This laptop for ten thousand dollars is **a steal**.", exampleZh: "這台筆電只要一萬元真的超划算。" },
  { word: "cost an arm and a leg", pos: "phr.", zh: "非常貴", level: "口語", tag: "購物消費", example: "That designer bag must **cost an arm and a leg**.", exampleZh: "那個名牌包一定貴得要命。" },
  { word: "on sale", pos: "phr.", zh: "特價中", level: "L2", tag: "購物消費", example: "These sneakers are **on sale** this week.", exampleZh: "這雙球鞋這禮拜特價中。" },
  { word: "warranty", pos: "n.", zh: "保固", level: "L5", tag: "購物消費", example: "The phone comes with a one-year **warranty**.", exampleZh: "這支手機附一年保固。" },

  // ===== 交通旅遊 Travel =====
  { word: "travel", pos: "v.", zh: "旅行", level: "L1", tag: "交通旅遊", example: "I love to **travel** during summer vacation.", exampleZh: "我很喜歡在暑假旅行。" },
  { word: "trip", pos: "n.", zh: "旅程", level: "L1", tag: "交通旅遊", example: "Our class **trip** to Kenting was so much fun.", exampleZh: "我們班去墾丁的校外旅行超好玩。" },
  { word: "airport", pos: "n.", zh: "機場", level: "L1", tag: "交通旅遊", example: "My uncle picked me up at the **airport**.", exampleZh: "我叔叔到機場來接我。" },
  { word: "ticket", pos: "n.", zh: "票", level: "L1", tag: "交通旅遊", example: "I already bought my train **ticket**.", exampleZh: "我已經買好火車票了。" },
  { word: "luggage", pos: "n.", zh: "行李", level: "L2", tag: "交通旅遊", example: "Please keep an eye on your **luggage**.", exampleZh: "請看好你的行李。" },
  { word: "passport", pos: "n.", zh: "護照", level: "L2", tag: "交通旅遊", example: "Don't forget to bring your **passport** to the airport.", exampleZh: "別忘了帶護照去機場。" },
  { word: "flight", pos: "n.", zh: "班機", level: "L2", tag: "交通旅遊", example: "Our **flight** to Tokyo leaves at 9 a.m.", exampleZh: "我們飛東京的班機早上九點起飛。" },
  { word: "delay", pos: "n.", zh: "延誤", level: "L3", tag: "交通旅遊", example: "There was a two-hour **delay** because of the storm.", exampleZh: "因為暴風雨班機延誤了兩小時。" },
  { word: "destination", pos: "n.", zh: "目的地", level: "L3", tag: "交通旅遊", example: "Kyoto is a popular travel **destination**.", exampleZh: "京都是一個很受歡迎的旅遊目的地。" },
  { word: "itinerary", pos: "n.", zh: "行程表", level: "L5", tag: "交通旅遊", example: "She planned the whole **itinerary** for our trip.", exampleZh: "她規劃了我們這趟旅行的整個行程表。" },
  { word: "subway", pos: "n.", zh: "地鐵", level: "L1", tag: "交通旅遊", example: "We took the **subway** to the museum.", exampleZh: "我們搭地鐵去博物館。" },
  { word: "platform", pos: "n.", zh: "月台", level: "L2", tag: "交通旅遊", example: "The train will arrive at **platform** three.", exampleZh: "火車將會抵達第三月台。" },
  { word: "transfer", pos: "v.", zh: "轉乘", level: "L3", tag: "交通旅遊", example: "You need to **transfer** to the red line at this station.", exampleZh: "你需要在這站轉乘紅線。" },
  { word: "traffic jam", pos: "n.", zh: "塞車", level: "L2", tag: "交通旅遊", example: "We got stuck in a **traffic jam** on the highway.", exampleZh: "我們在高速公路上塞車動彈不得。" },
  { word: "crosswalk", pos: "n.", zh: "斑馬線", level: "L2", tag: "交通旅遊", example: "Always cross the street at the **crosswalk**.", exampleZh: "過馬路時一定要走斑馬線。" },
  { word: "sightseeing", pos: "n.", zh: "觀光", level: "L3", tag: "交通旅遊", example: "We spent the whole day **sightseeing** in the old town.", exampleZh: "我們一整天都在舊城區觀光。" },
  { word: "souvenir", pos: "n.", zh: "紀念品", level: "L3", tag: "交通旅遊", example: "I bought a small **souvenir** for my sister.", exampleZh: "我買了一個小紀念品給我妹妹。" },
  { word: "accommodation", pos: "n.", zh: "住宿", level: "L5", tag: "交通旅遊", example: "We booked our **accommodation** near the beach.", exampleZh: "我們訂了海邊附近的住宿。" },
  { word: "tour guide", pos: "n.", zh: "導遊", level: "L2", tag: "交通旅遊", example: "Our **tour guide** spoke both English and Japanese.", exampleZh: "我們的導遊會說英文和日文。" },
  { word: "jet lag", pos: "n.", zh: "時差", level: "L4", tag: "交通旅遊", example: "I felt terrible **jet lag** after the long flight.", exampleZh: "長途飛行後我時差很嚴重。" },
  { word: "layover", pos: "n.", zh: "轉機停留", level: "口語", tag: "交通旅遊", example: "We had a three-hour **layover** in Hong Kong.", exampleZh: "我們在香港轉機停留了三小時。" },
  { word: "road trip", pos: "n.", zh: "公路旅行", level: "口語", tag: "交通旅遊", example: "We're planning a **road trip** along the coast.", exampleZh: "我們正在計畫一趟沿海的公路旅行。" },
  { word: "off the beaten path", pos: "phr.", zh: "人煙稀少的地方", level: "口語", tag: "交通旅遊", example: "This little village is really **off the beaten path**.", exampleZh: "這個小村莊真的很人煙稀少。" },
  { word: "miss the bus", pos: "phr.", zh: "錯過公車", level: "口語", tag: "交通旅遊", example: "I **missed the bus** and had to wait twenty minutes.", exampleZh: "我錯過公車，只好等二十分鐘。" },
  { word: "catch a flight", pos: "phr.", zh: "趕上班機", level: "L3", tag: "交通旅遊", example: "We rushed to **catch a flight** to Osaka.", exampleZh: "我們趕著去搭飛往大阪的班機。" },
  { word: "backpacking", pos: "n.", zh: "背包旅行", level: "L4", tag: "交通旅遊", example: "He went **backpacking** through Southeast Asia last year.", exampleZh: "他去年去東南亞背包旅行。" },
  { word: "customs", pos: "n.", zh: "海關", level: "L4", tag: "交通旅遊", example: "We waited in line at **customs** for an hour.", exampleZh: "我們在海關排隊排了一小時。" },

  // ===== 學校學習 School =====
  { word: "study", pos: "v.", zh: "讀書", level: "L1", tag: "學校學習", example: "I need to **study** for my math test tonight.", exampleZh: "我今晚需要讀書準備數學考試。" },
  { word: "homework", pos: "n.", zh: "功課", level: "L1", tag: "學校學習", example: "I finished my **homework** before dinner.", exampleZh: "我在晚餐前寫完了功課。" },
  { word: "exam", pos: "n.", zh: "考試", level: "L1", tag: "學校學習", example: "The English **exam** is next Monday.", exampleZh: "英文考試是下週一。" },
  { word: "grade", pos: "n.", zh: "成績", level: "L1", tag: "學校學習", example: "She got a good **grade** on her science project.", exampleZh: "她的自然科學專題拿到很好的成績。" },
  { word: "classmate", pos: "n.", zh: "同學", level: "L1", tag: "學校學習", example: "My **classmate** helped me with the assignment.", exampleZh: "我同學幫我完成了那份作業。" },
  { word: "teacher", pos: "n.", zh: "老師", level: "L1", tag: "學校學習", example: "Our **teacher** explained the lesson very clearly.", exampleZh: "我們的老師把這課解釋得很清楚。" },
  { word: "subject", pos: "n.", zh: "科目", level: "L1", tag: "學校學習", example: "History is my favorite **subject**.", exampleZh: "歷史是我最喜歡的科目。" },
  { word: "textbook", pos: "n.", zh: "課本", level: "L2", tag: "學校學習", example: "I forgot to bring my English **textbook**.", exampleZh: "我忘記帶我的英文課本了。" },
  { word: "lecture", pos: "n.", zh: "講課", level: "L3", tag: "學校學習", example: "The **lecture** on climate change was interesting.", exampleZh: "那堂關於氣候變遷的講課很有趣。" },
  { word: "assignment", pos: "n.", zh: "作業", level: "L3", tag: "學校學習", example: "Our teacher gave us a group **assignment**.", exampleZh: "老師給我們一份小組作業。" },
  { word: "deadline", pos: "n.", zh: "截止日期", level: "L3", tag: "學校學習", example: "The **deadline** for the essay is Friday.", exampleZh: "這篇文章的截止日期是星期五。" },
  { word: "review", pos: "v.", zh: "複習", level: "L2", tag: "學校學習", example: "Let's **review** the vocabulary before the quiz.", exampleZh: "我們在小考前先複習一下單字吧。" },
  { word: "memorize", pos: "v.", zh: "背誦", level: "L3", tag: "學校學習", example: "I need to **memorize** these ten new words.", exampleZh: "我需要背這十個新單字。" },
  { word: "concentrate", pos: "v.", zh: "專心", level: "L3", tag: "學校學習", example: "It's hard to **concentrate** with all this noise.", exampleZh: "在這麼吵的環境下很難專心。" },
  { word: "scholarship", pos: "n.", zh: "獎學金", level: "L4", tag: "學校學習", example: "She won a **scholarship** to study abroad.", exampleZh: "她拿到一筆獎學金可以出國唸書。" },
  { word: "graduate", pos: "v.", zh: "畢業", level: "L3", tag: "學校學習", example: "My brother will **graduate** from high school next year.", exampleZh: "我哥哥明年要從高中畢業了。" },
  { word: "semester", pos: "n.", zh: "學期", level: "L2", tag: "學校學習", example: "This **semester** has been really busy.", exampleZh: "這個學期真的很忙。" },
  { word: "curriculum", pos: "n.", zh: "課程", level: "L5", tag: "學校學習", example: "The school updated its English **curriculum** this year.", exampleZh: "學校今年更新了英文課程。" },
  { word: "cram school", pos: "n.", zh: "補習班", level: "L2", tag: "學校學習", example: "Many students go to **cram school** after class.", exampleZh: "很多學生放學後會去補習班。" },
  { word: "procrastinate", pos: "v.", zh: "拖延", level: "L5", tag: "學校學習", example: "I always **procrastinate** before big exams.", exampleZh: "我在大考前總是會拖延。" },
  { word: "cram", pos: "v.", zh: "臨時抱佛腳", level: "口語", tag: "學校學習", example: "I had to **cram** for the history test last night.", exampleZh: "我昨晚為了歷史考試臨時抱佛腳。" },
  { word: "pull an all-nighter", pos: "phr.", zh: "熬夜通宵", level: "口語", tag: "學校學習", example: "He **pulled an all-nighter** to finish his report.", exampleZh: "他熬夜通宵才把報告寫完。" },
  { word: "ace", pos: "v.", zh: "考得很好", level: "口語", tag: "學校學習", example: "I hope I can **ace** this exam.", exampleZh: "我希望這次考試能考得超好。" },
  { word: "hit the books", pos: "phr.", zh: "用功讀書", level: "口語", tag: "學校學習", example: "It's time to **hit the books** before finals.", exampleZh: "期末考前該用功讀書了。" },
  { word: "plagiarism", pos: "n.", zh: "抄襲", level: "L6", tag: "學校學習", example: "**Plagiarism** can get you a failing grade.", exampleZh: "抄襲可能會讓你這科被當掉。" },
  { word: "attendance", pos: "n.", zh: "出席", level: "L3", tag: "學校學習", example: "The teacher checks **attendance** every morning.", exampleZh: "老師每天早上都會點名確認出席。" },
  { word: "tuition", pos: "n.", zh: "學費", level: "L4", tag: "學校學習", example: "College **tuition** keeps getting more expensive.", exampleZh: "大學學費越來越貴了。" },

  // ===== 社群網路 Social Media =====
  { word: "post", pos: "v.", zh: "發文", level: "L2", tag: "社群網路", example: "I **posted** a photo from our trip.", exampleZh: "我發了一張我們旅行的照片。" },
  { word: "comment", pos: "n.", zh: "留言", level: "L2", tag: "社群網路", example: "She left a funny **comment** on my post.", exampleZh: "她在我的貼文下留了一則有趣的留言。" },
  { word: "follower", pos: "n.", zh: "追蹤者", level: "L2", tag: "社群網路", example: "His account has over a million **followers**.", exampleZh: "他的帳號有超過一百萬個追蹤者。" },
  { word: "like", pos: "v.", zh: "按讚", level: "L1", tag: "社群網路", example: "Don't forget to **like** the video.", exampleZh: "別忘了幫這部影片按讚。" },
  { word: "share", pos: "v.", zh: "分享", level: "L1", tag: "社群網路", example: "I want to **share** this article with you.", exampleZh: "我想跟你分享這篇文章。" },
  { word: "hashtag", pos: "n.", zh: "主題標籤", level: "L3", tag: "社群網路", example: "She added a **hashtag** to reach more people.", exampleZh: "她加了一個主題標籤來觸及更多人。" },
  { word: "profile", pos: "n.", zh: "個人檔案", level: "L2", tag: "社群網路", example: "Please update your **profile** picture.", exampleZh: "請更新你的個人檔案照片。" },
  { word: "update", pos: "v.", zh: "更新", level: "L2", tag: "社群網路", example: "I need to **update** the app on my phone.", exampleZh: "我需要更新手機上的這個App。" },
  { word: "livestream", pos: "n.", zh: "直播", level: "L3", tag: "社群網路", example: "The singer did a **livestream** last night.", exampleZh: "那位歌手昨晚做了一場直播。" },
  { word: "influencer", pos: "n.", zh: "網紅", level: "L4", tag: "社群網路", example: "That **influencer** reviews makeup products.", exampleZh: "那位網紅會評論化妝品。" },
  { word: "viral", pos: "adj.", zh: "爆紅的", level: "L4", tag: "社群網路", example: "The funny video became **viral** overnight.", exampleZh: "那部好笑的影片一夜之間爆紅。" },
  { word: "notification", pos: "n.", zh: "通知", level: "L3", tag: "社群網路", example: "My phone keeps buzzing with **notifications**.", exampleZh: "我的手機一直因為通知而震動。" },
  { word: "block", pos: "v.", zh: "封鎖", level: "L2", tag: "社群網路", example: "I decided to **block** that stranger.", exampleZh: "我決定封鎖那個陌生人。" },
  { word: "privacy", pos: "n.", zh: "隱私", level: "L4", tag: "社群網路", example: "You should protect your online **privacy**.", exampleZh: "你應該保護你的網路隱私。" },
  { word: "username", pos: "n.", zh: "使用者名稱", level: "L2", tag: "社群網路", example: "Please enter your **username** and password.", exampleZh: "請輸入你的使用者名稱和密碼。" },
  { word: "download", pos: "v.", zh: "下載", level: "L2", tag: "社群網路", example: "I **downloaded** a new game last night.", exampleZh: "我昨晚下載了一款新遊戲。" },
  { word: "upload", pos: "v.", zh: "上傳", level: "L2", tag: "社群網路", example: "She **uploaded** the video this morning.", exampleZh: "她今天早上上傳了那部影片。" },
  { word: "meme", pos: "n.", zh: "迷因", level: "口語", tag: "社群網路", example: "He sent me a really funny **meme**.", exampleZh: "他傳給我一個超好笑的迷因。" },
  { word: "go viral", pos: "phr.", zh: "爆紅", level: "口語", tag: "社群網路", example: "The dance challenge **went viral** on social media.", exampleZh: "那個舞蹈挑戰在社群媒體上爆紅。" },
  { word: "DM", pos: "n./v.", zh: "私訊", level: "口語", tag: "社群網路", example: "Just **DM** me if you have any questions.", exampleZh: "如果你有任何問題就私訊我。" },
  { word: "ghost", pos: "v.", zh: "已讀不回、突然消失", level: "口語", tag: "社群網路", example: "He **ghosted** me after our first date.", exampleZh: "他在我們第一次約會後就消失不回訊息了。" },
  { word: "troll", pos: "n./v.", zh: "酸民、挑釁", level: "口語", tag: "社群網路", example: "Don't feed the **trolls** in the comments.", exampleZh: "不要理留言區裡的酸民。" },
  { word: "selfie", pos: "n.", zh: "自拍", level: "L2", tag: "社群網路", example: "Let's take a **selfie** in front of the fountain.", exampleZh: "我們在噴泉前自拍一張吧。" },
  { word: "filter", pos: "n.", zh: "濾鏡", level: "L2", tag: "社群網路", example: "This app has a cute puppy **filter**.", exampleZh: "這個App有一個可愛的小狗濾鏡。" },
  { word: "subscribe", pos: "v.", zh: "訂閱", level: "L3", tag: "社群網路", example: "Please **subscribe** to my channel.", exampleZh: "請訂閱我的頻道。" },
  { word: "algorithm", pos: "n.", zh: "演算法", level: "L5", tag: "社群網路", example: "The **algorithm** decides what videos you see.", exampleZh: "演算法決定了你會看到哪些影片。" },
  { word: "emoji", pos: "n.", zh: "表情符號", level: "L2", tag: "社群網路", example: "She replied with just a heart **emoji**.", exampleZh: "她只回了一個愛心表情符號。" },

  // ===== 情緒個性 Emotion & Personality =====
  { word: "happy", pos: "adj.", zh: "快樂的", level: "L1", tag: "情緒個性", example: "I feel really **happy** today.", exampleZh: "我今天覺得很快樂。" },
  { word: "sad", pos: "adj.", zh: "難過的", level: "L1", tag: "情緒個性", example: "She looked **sad** after the movie ended.", exampleZh: "電影結束後她看起來很難過。" },
  { word: "angry", pos: "adj.", zh: "生氣的", level: "L1", tag: "情緒個性", example: "He got **angry** when he lost the game.", exampleZh: "他輸掉比賽時很生氣。" },
  { word: "nervous", pos: "adj.", zh: "緊張的", level: "L2", tag: "情緒個性", example: "I was so **nervous** before my speech.", exampleZh: "我在演講前非常緊張。" },
  { word: "excited", pos: "adj.", zh: "興奮的", level: "L2", tag: "情緒個性", example: "We're all **excited** about the concert tonight.", exampleZh: "我們都對今晚的演唱會很興奮。" },
  { word: "bored", pos: "adj.", zh: "無聊的", level: "L2", tag: "情緒個性", example: "I get **bored** easily during long meetings.", exampleZh: "我在冗長的會議中很容易感到無聊。" },
  { word: "confident", pos: "adj.", zh: "有自信的", level: "L3", tag: "情緒個性", example: "She felt **confident** about the interview.", exampleZh: "她對這次面試感到很有自信。" },
  { word: "shy", pos: "adj.", zh: "害羞的", level: "L2", tag: "情緒個性", example: "He's too **shy** to talk to new people.", exampleZh: "他害羞到不敢跟新朋友說話。" },
  { word: "jealous", pos: "adj.", zh: "嫉妒的", level: "L3", tag: "情緒個性", example: "I felt a little **jealous** of her new phone.", exampleZh: "我對她的新手機有點嫉妒。" },
  { word: "embarrassed", pos: "adj.", zh: "尷尬的", level: "L3", tag: "情緒個性", example: "I was so **embarrassed** when I tripped in class.", exampleZh: "我在課堂上絆倒時覺得超尷尬。" },
  { word: "curious", pos: "adj.", zh: "好奇的", level: "L2", tag: "情緒個性", example: "I'm **curious** about how this app works.", exampleZh: "我很好奇這個App是怎麼運作的。" },
  { word: "stubborn", pos: "adj.", zh: "固執的", level: "L4", tag: "情緒個性", example: "My grandpa can be really **stubborn**.", exampleZh: "我爺爺有時候真的很固執。" },
  { word: "optimistic", pos: "adj.", zh: "樂觀的", level: "L4", tag: "情緒個性", example: "She stays **optimistic** even when things go wrong.", exampleZh: "就算事情不順利，她還是保持樂觀。" },
  { word: "pessimistic", pos: "adj.", zh: "悲觀的", level: "L5", tag: "情緒個性", example: "Try not to be so **pessimistic** about the future.", exampleZh: "試著別對未來這麼悲觀。" },
  { word: "generous", pos: "adj.", zh: "慷慨的", level: "L3", tag: "情緒個性", example: "It was **generous** of him to share his lunch.", exampleZh: "他願意分享午餐真的很慷慨。" },
  { word: "selfish", pos: "adj.", zh: "自私的", level: "L3", tag: "情緒個性", example: "It's **selfish** to keep all the credit for yourself.", exampleZh: "把功勞都留給自己是很自私的。" },
  { word: "moody", pos: "adj.", zh: "情緒化的", level: "L4", tag: "情緒個性", example: "He's been really **moody** since the exam.", exampleZh: "他自從考試後情緒就很不穩定。" },
  { word: "anxious", pos: "adj.", zh: "焦慮的", level: "L4", tag: "情緒個性", example: "I feel **anxious** whenever I have a test.", exampleZh: "每次考試我都覺得很焦慮。" },
  { word: "grateful", pos: "adj.", zh: "感激的", level: "L4", tag: "情緒個性", example: "I'm **grateful** for all your help.", exampleZh: "我很感激你所有的幫忙。" },
  { word: "lonely", pos: "adj.", zh: "孤單的", level: "L2", tag: "情緒個性", example: "She felt **lonely** on her first day at school.", exampleZh: "她在學校的第一天覺得很孤單。" },
  { word: "over the moon", pos: "phr.", zh: "非常開心", level: "口語", tag: "情緒個性", example: "I was **over the moon** when I passed the exam.", exampleZh: "我通過考試時開心得不得了。" },
  { word: "down in the dumps", pos: "phr.", zh: "心情低落", level: "口語", tag: "情緒個性", example: "He's been **down in the dumps** all week.", exampleZh: "他這整個禮拜心情都很低落。" },
  { word: "freak out", pos: "phr.", zh: "抓狂", level: "口語", tag: "情緒個性", example: "Don't **freak out**, we still have time.", exampleZh: "別抓狂，我們還有時間。" },
  { word: "chill out", pos: "phr.", zh: "放輕鬆", level: "口語", tag: "情緒個性", example: "Just **chill out**, everything will be fine.", exampleZh: "放輕鬆，一切都會沒事的。" },
  { word: "butterflies in one's stomach", pos: "phr.", zh: "忐忑不安", level: "口語", tag: "情緒個性", example: "I got **butterflies in my stomach** before the game.", exampleZh: "比賽前我覺得非常忐忑不安。" },
  { word: "blue", pos: "adj.", zh: "憂鬱的", level: "口語", tag: "情緒個性", example: "I've been feeling a little **blue** lately.", exampleZh: "我最近心情有點低落。" },
  { word: "touched", pos: "adj.", zh: "感動的", level: "L3", tag: "情緒個性", example: "I was really **touched** by her kind letter.", exampleZh: "她那封貼心的信讓我很感動。" },

  // ===== 健康身體 Health =====
  { word: "healthy", pos: "adj.", zh: "健康的", level: "L1", tag: "健康身體", example: "Eating vegetables keeps you **healthy**.", exampleZh: "吃蔬菜能讓你保持健康。" },
  { word: "sick", pos: "adj.", zh: "生病的", level: "L1", tag: "健康身體", example: "I stayed home because I was **sick**.", exampleZh: "我因為生病所以待在家。" },
  { word: "fever", pos: "n.", zh: "發燒", level: "L2", tag: "健康身體", example: "He has a **fever** and a sore throat.", exampleZh: "他發燒又喉嚨痛。" },
  { word: "headache", pos: "n.", zh: "頭痛", level: "L1", tag: "健康身體", example: "I have a terrible **headache** today.", exampleZh: "我今天頭痛得很嚴重。" },
  { word: "cough", pos: "v.", zh: "咳嗽", level: "L2", tag: "健康身體", example: "She couldn't stop **coughing** in class.", exampleZh: "她在課堂上咳嗽個不停。" },
  { word: "medicine", pos: "n.", zh: "藥", level: "L1", tag: "健康身體", example: "Remember to take your **medicine** after lunch.", exampleZh: "記得午餐後要吃藥。" },
  { word: "hospital", pos: "n.", zh: "醫院", level: "L1", tag: "健康身體", example: "My mom works at the local **hospital**.", exampleZh: "我媽媽在當地的醫院工作。" },
  { word: "doctor", pos: "n.", zh: "醫生", level: "L1", tag: "健康身體", example: "The **doctor** told me to get more rest.", exampleZh: "醫生要我多休息。" },
  { word: "injury", pos: "n.", zh: "受傷", level: "L3", tag: "健康身體", example: "He got a knee **injury** during the game.", exampleZh: "他在比賽中膝蓋受傷了。" },
  { word: "exercise", pos: "v.", zh: "運動", level: "L1", tag: "健康身體", example: "I try to **exercise** every morning.", exampleZh: "我每天早上都試著運動。" },
  { word: "diet", pos: "n.", zh: "飲食", level: "L2", tag: "健康身體", example: "A balanced **diet** is important for your health.", exampleZh: "均衡的飲食對健康很重要。" },
  { word: "sleep", pos: "v.", zh: "睡覺", level: "L1", tag: "健康身體", example: "You should **sleep** eight hours a night.", exampleZh: "你每晚應該睡八小時。" },
  { word: "stress", pos: "n.", zh: "壓力", level: "L2", tag: "健康身體", example: "Too much **stress** can make you sick.", exampleZh: "太大的壓力會讓你生病。" },
  { word: "allergy", pos: "n.", zh: "過敏", level: "L3", tag: "健康身體", example: "I have an **allergy** to peanuts.", exampleZh: "我對花生過敏。" },
  { word: "symptom", pos: "n.", zh: "症狀", level: "L4", tag: "健康身體", example: "A fever is a common **symptom** of the flu.", exampleZh: "發燒是流感常見的症狀。" },
  { word: "checkup", pos: "n.", zh: "健康檢查", level: "L3", tag: "健康身體", example: "I have a dental **checkup** next week.", exampleZh: "我下週有一次牙齒健康檢查。" },
  { word: "vitamin", pos: "n.", zh: "維他命", level: "L3", tag: "健康身體", example: "Oranges are full of **vitamin** C.", exampleZh: "柳橙富含維他命C。" },
  { word: "immune system", pos: "n.", zh: "免疫系統", level: "L5", tag: "健康身體", example: "Sleep helps strengthen your **immune system**.", exampleZh: "睡眠有助於增強你的免疫系統。" },
  { word: "surgery", pos: "n.", zh: "手術", level: "L4", tag: "健康身體", example: "He needs **surgery** on his broken arm.", exampleZh: "他斷掉的手臂需要動手術。" },
  { word: "recover", pos: "v.", zh: "康復", level: "L3", tag: "健康身體", example: "It took her a week to **recover** from the flu.", exampleZh: "她花了一週的時間從流感中康復。" },
  { word: "under the weather", pos: "phr.", zh: "身體不適", level: "口語", tag: "健康身體", example: "I'm feeling a bit **under the weather** today.", exampleZh: "我今天覺得有點不太舒服。" },
  { word: "run down", pos: "adj.", zh: "疲憊虛弱", level: "口語", tag: "健康身體", example: "I feel really **run down** after finals week.", exampleZh: "期末考週後我覺得非常疲憊虛弱。" },
  { word: "work out", pos: "phr.", zh: "健身運動", level: "口語", tag: "健康身體", example: "I **work out** at the gym three times a week.", exampleZh: "我一週去健身房運動三次。" },
  { word: "catch a cold", pos: "phr.", zh: "感冒", level: "L2", tag: "健康身體", example: "I **caught a cold** from swimming in the rain.", exampleZh: "我因為在雨中游泳而感冒了。" },
  { word: "throw up", pos: "phr.", zh: "嘔吐", level: "口語", tag: "健康身體", example: "He felt sick and had to **throw up**.", exampleZh: "他覺得不舒服然後嘔吐了。" },
  { word: "energetic", pos: "adj.", zh: "精力充沛的", level: "L3", tag: "健康身體", example: "She always feels **energetic** in the morning.", exampleZh: "她早上總是精力充沛。" },
  { word: "posture", pos: "n.", zh: "姿勢", level: "L4", tag: "健康身體", example: "Sitting up straight improves your **posture**.", exampleZh: "坐直可以改善你的姿勢。" },

  // ===== 居家日常 Home =====
  { word: "clean", pos: "v.", zh: "打掃", level: "L1", tag: "居家日常", example: "We **clean** our room every Saturday.", exampleZh: "我們每個星期六都會打掃房間。" },
  { word: "cook", pos: "v.", zh: "煮飯", level: "L1", tag: "居家日常", example: "My dad likes to **cook** dinner on weekends.", exampleZh: "我爸爸喜歡在週末煮晚餐。" },
  { word: "laundry", pos: "n.", zh: "洗衣", level: "L2", tag: "居家日常", example: "I need to do the **laundry** tonight.", exampleZh: "我今晚需要洗衣服。" },
  { word: "chore", pos: "n.", zh: "家事", level: "L3", tag: "居家日常", example: "Taking out the trash is my daily **chore**.", exampleZh: "倒垃圾是我每天的家事。" },
  { word: "furniture", pos: "n.", zh: "家具", level: "L2", tag: "居家日常", example: "We bought new **furniture** for the living room.", exampleZh: "我們幫客廳買了新家具。" },
  { word: "kitchen", pos: "n.", zh: "廚房", level: "L1", tag: "居家日常", example: "The **kitchen** smells like fresh bread.", exampleZh: "廚房聞起來有剛出爐麵包的香味。" },
  { word: "bedroom", pos: "n.", zh: "臥室", level: "L1", tag: "居家日常", example: "I painted my **bedroom** wall light blue.", exampleZh: "我把我臥室的牆漆成淺藍色。" },
  { word: "bathroom", pos: "n.", zh: "浴室", level: "L1", tag: "居家日常", example: "The **bathroom** light isn't working.", exampleZh: "浴室的燈壞掉了。" },
  { word: "neighbor", pos: "n.", zh: "鄰居", level: "L2", tag: "居家日常", example: "Our **neighbor** brought us some homemade cookies.", exampleZh: "我們的鄰居送了我們一些自製餅乾。" },
  { word: "rent", pos: "v.", zh: "租", level: "L2", tag: "居家日常", example: "They **rent** a small apartment near the school.", exampleZh: "他們在學校附近租了一間小公寓。" },
  { word: "roommate", pos: "n.", zh: "室友", level: "L2", tag: "居家日常", example: "My **roommate** and I share the cleaning duties.", exampleZh: "我跟我室友一起分擔打掃的工作。" },
  { word: "appliance", pos: "n.", zh: "家電", level: "L4", tag: "居家日常", example: "The new **appliance** saves us a lot of time.", exampleZh: "這台新家電幫我們省下很多時間。" },
  { word: "tidy", pos: "adj.", zh: "整齊的", level: "L3", tag: "居家日常", example: "Please keep your desk **tidy**.", exampleZh: "請保持你的書桌整齊。" },
  { word: "messy", pos: "adj.", zh: "凌亂的", level: "L2", tag: "居家日常", example: "His room is always so **messy**.", exampleZh: "他的房間總是很凌亂。" },
  { word: "garbage", pos: "n.", zh: "垃圾", level: "L2", tag: "居家日常", example: "Please take the **garbage** out before you leave.", exampleZh: "你離開前請把垃圾拿出去。" },
  { word: "vacuum", pos: "v.", zh: "用吸塵器打掃", level: "L3", tag: "居家日常", example: "I need to **vacuum** the living room carpet.", exampleZh: "我需要用吸塵器清潔客廳的地毯。" },
  { word: "utility bill", pos: "n.", zh: "水電費帳單", level: "L4", tag: "居家日常", example: "We pay the **utility bill** at the end of the month.", exampleZh: "我們每個月底繳水電費帳單。" },
  { word: "mow the lawn", pos: "phr.", zh: "割草", level: "口語", tag: "居家日常", example: "My dad **mows the lawn** every weekend.", exampleZh: "我爸爸每個週末都會割草。" },
  { word: "do the dishes", pos: "phr.", zh: "洗碗", level: "口語", tag: "居家日常", example: "It's your turn to **do the dishes** tonight.", exampleZh: "今晚輪到你洗碗了。" },
  { word: "take out the trash", pos: "phr.", zh: "倒垃圾", level: "口語", tag: "居家日常", example: "Can you **take out the trash** before dinner?", exampleZh: "你可以在晚餐前倒垃圾嗎？" },
  { word: "couch potato", pos: "n.", zh: "懶骨頭、整天窩沙發的人", level: "口語", tag: "居家日常", example: "Don't be such a **couch potato** all weekend.", exampleZh: "整個週末別當個懶骨頭。" },
  { word: "cozy", pos: "adj.", zh: "舒適的", level: "口語", tag: "居家日常", example: "This blanket makes my room feel so **cozy**.", exampleZh: "這條毯子讓我的房間感覺好舒適。" },
  { word: "renovate", pos: "v.", zh: "裝修", level: "L5", tag: "居家日常", example: "They plan to **renovate** the old kitchen.", exampleZh: "他們計畫要裝修那個老舊的廚房。" },
  { word: "household", pos: "adj.", zh: "家庭的", level: "L3", tag: "居家日常", example: "Everyone shares the **household** chores here.", exampleZh: "這裡每個人都會分擔家務。" },
  { word: "décor", pos: "n.", zh: "裝潢", level: "L4", tag: "居家日常", example: "I love the simple **décor** in this cafe.", exampleZh: "我很喜歡這間咖啡廳簡約的裝潢。" },
  { word: "plug in", pos: "phr.", zh: "插電", level: "L2", tag: "居家日常", example: "Don't forget to **plug in** your phone tonight.", exampleZh: "今晚別忘了幫手機插電充電。" },

  // ===== 人際社交 Relationships =====
  { word: "friend", pos: "n.", zh: "朋友", level: "L1", tag: "人際社交", example: "She's been my best **friend** since elementary school.", exampleZh: "她從小學開始就是我最好的朋友。" },
  { word: "friendship", pos: "n.", zh: "友誼", level: "L2", tag: "人際社交", example: "Our **friendship** has lasted for ten years.", exampleZh: "我們的友誼已經維持十年了。" },
  { word: "trust", pos: "v.", zh: "信任", level: "L2", tag: "人際社交", example: "I **trust** you with my secret.", exampleZh: "我信任你，把我的秘密告訴你。" },
  { word: "honest", pos: "adj.", zh: "誠實的", level: "L2", tag: "人際社交", example: "Please be **honest** with me about what happened.", exampleZh: "請誠實告訴我發生了什麼事。" },
  { word: "loyal", pos: "adj.", zh: "忠誠的", level: "L4", tag: "人際社交", example: "A good friend is always **loyal**.", exampleZh: "一個好朋友總是忠誠的。" },
  { word: "argue", pos: "v.", zh: "爭吵", level: "L2", tag: "人際社交", example: "The two brothers **argue** about small things.", exampleZh: "這對兄弟常為了小事爭吵。" },
  { word: "apologize", pos: "v.", zh: "道歉", level: "L3", tag: "人際社交", example: "He called to **apologize** for being late.", exampleZh: "他打電話來為遲到道歉。" },
  { word: "forgive", pos: "v.", zh: "原諒", level: "L3", tag: "人際社交", example: "It took her a while to **forgive** him.", exampleZh: "她花了一段時間才原諒他。" },
  { word: "gossip", pos: "n./v.", zh: "八卦", level: "L3", tag: "人際社交", example: "I don't like to **gossip** about my classmates.", exampleZh: "我不喜歡八卦我的同學。" },
  { word: "introduce", pos: "v.", zh: "介紹", level: "L2", tag: "人際社交", example: "Let me **introduce** you to my best friend.", exampleZh: "讓我把你介紹給我最好的朋友。" },
  { word: "stranger", pos: "n.", zh: "陌生人", level: "L2", tag: "人際社交", example: "Never get in a car with a **stranger**.", exampleZh: "絕對不要上陌生人的車。" },
  { word: "relationship", pos: "n.", zh: "關係", level: "L3", tag: "人際社交", example: "They have a close **relationship**.", exampleZh: "他們的關係很親近。" },
  { word: "couple", pos: "n.", zh: "情侶", level: "L2", tag: "人際社交", example: "The **couple** met in their freshman year.", exampleZh: "這對情侶是在大一時認識的。" },
  { word: "breakup", pos: "n.", zh: "分手", level: "L3", tag: "人際社交", example: "She was upset after the **breakup**.", exampleZh: "她在分手後很難過。" },
  { word: "crush", pos: "n.", zh: "暗戀對象", level: "口語", tag: "人際社交", example: "I've had a **crush** on him since last year.", exampleZh: "我從去年就開始暗戀他了。" },
  { word: "BFF", pos: "n.", zh: "最要好的朋友", level: "口語", tag: "人際社交", example: "She's my **BFF**, we tell each other everything.", exampleZh: "她是我最要好的朋友，我們什麼都跟彼此說。" },
  { word: "hang out", pos: "phr.", zh: "出去玩、相聚", level: "口語", tag: "人際社交", example: "Do you want to **hang out** this weekend?", exampleZh: "這個週末你想出去玩嗎？" },
  { word: "get along with", pos: "phr.", zh: "與...相處融洽", level: "L3", tag: "人際社交", example: "I **get along with** all of my classmates.", exampleZh: "我跟我所有的同學都相處融洽。" },
  { word: "hit it off", pos: "phr.", zh: "一拍即合", level: "口語", tag: "人際社交", example: "We **hit it off** the moment we met.", exampleZh: "我們一見面就一拍即合。" },
  { word: "text back", pos: "phr.", zh: "回訊息", level: "口語", tag: "人際社交", example: "Why didn't you **text back** last night?", exampleZh: "你昨晚為什麼沒有回訊息？" },
  { word: "peer pressure", pos: "n.", zh: "同儕壓力", level: "L4", tag: "人際社交", example: "He felt **peer pressure** to try smoking.", exampleZh: "他因為同儕壓力而想嘗試抽菸。" },
  { word: "acquaintance", pos: "n.", zh: "認識的人", level: "L5", tag: "人際社交", example: "He's just an **acquaintance**, not a close friend.", exampleZh: "他只是個認識的人，不是親近的朋友。" },
  { word: "sincere", pos: "adj.", zh: "真誠的", level: "L4", tag: "人際社交", example: "Her apology sounded really **sincere**.", exampleZh: "她的道歉聽起來很真誠。" },
  { word: "betray", pos: "v.", zh: "背叛", level: "L5", tag: "人際社交", example: "I never thought he would **betray** my trust.", exampleZh: "我從沒想過他會背叛我的信任。" },
  { word: "reunion", pos: "n.", zh: "團聚", level: "L4", tag: "人際社交", example: "Our class **reunion** is planned for next month.", exampleZh: "我們的同學會計畫在下個月舉行。" },
  { word: "small talk", pos: "n.", zh: "閒聊", level: "口語", tag: "人際社交", example: "We made **small talk** while waiting for the bus.", exampleZh: "我們在等公車時閒聊了一下。" },

  // ===== 娛樂休閒 Entertainment =====
  { word: "movie", pos: "n.", zh: "電影", level: "L1", tag: "娛樂休閒", example: "We watched a **movie** at the theater.", exampleZh: "我們在電影院看了一部電影。" },
  { word: "concert", pos: "n.", zh: "演唱會", level: "L2", tag: "娛樂休閒", example: "The **concert** tickets sold out in minutes.", exampleZh: "演唱會門票幾分鐘內就賣光了。" },
  { word: "game", pos: "n.", zh: "遊戲", level: "L1", tag: "娛樂休閒", example: "Let's play a board **game** tonight.", exampleZh: "我們今晚來玩桌遊吧。" },
  { word: "hobby", pos: "n.", zh: "嗜好", level: "L2", tag: "娛樂休閒", example: "Drawing is my favorite **hobby**.", exampleZh: "畫畫是我最喜歡的嗜好。" },
  { word: "relax", pos: "v.", zh: "放鬆", level: "L2", tag: "娛樂休閒", example: "I like to **relax** by listening to music.", exampleZh: "我喜歡用聽音樂來放鬆。" },
  { word: "weekend", pos: "n.", zh: "週末", level: "L1", tag: "娛樂休閒", example: "What are your plans for the **weekend**?", exampleZh: "你這個週末有什麼計畫？" },
  { word: "amusement park", pos: "n.", zh: "遊樂園", level: "L2", tag: "娛樂休閒", example: "We spent the whole day at the **amusement park**.", exampleZh: "我們一整天都待在遊樂園。" },
  { word: "karaoke", pos: "n.", zh: "卡拉OK", level: "L2", tag: "娛樂休閒", example: "Let's go sing **karaoke** after dinner.", exampleZh: "晚餐後我們去唱卡拉OK吧。" },
  { word: "board game", pos: "n.", zh: "桌遊", level: "L2", tag: "娛樂休閒", example: "This **board game** takes about an hour to play.", exampleZh: "這款桌遊大概要玩一個小時。" },
  { word: "novel", pos: "n.", zh: "小說", level: "L2", tag: "娛樂休閒", example: "I just finished reading a great **novel**.", exampleZh: "我剛讀完一本很棒的小說。" },
  { word: "exhibition", pos: "n.", zh: "展覽", level: "L3", tag: "娛樂休閒", example: "The art **exhibition** runs until next month.", exampleZh: "這場藝術展覽會展到下個月。" },
  { word: "band", pos: "n.", zh: "樂團", level: "L2", tag: "娛樂休閒", example: "He plays guitar in a school **band**.", exampleZh: "他在校內樂團彈吉他。" },
  { word: "audience", pos: "n.", zh: "觀眾", level: "L3", tag: "娛樂休閒", example: "The **audience** cheered loudly after the show.", exampleZh: "表演結束後觀眾大聲歡呼。" },
  { word: "performance", pos: "n.", zh: "表演", level: "L3", tag: "娛樂休閒", example: "Her dance **performance** was amazing.", exampleZh: "她的舞蹈表演棒極了。" },
  { word: "binge-watch", pos: "v.", zh: "追劇", level: "口語", tag: "娛樂休閒", example: "We **binge-watched** the whole series in one weekend.", exampleZh: "我們一個週末就追完了整部影集。" },
  { word: "chill", pos: "v.", zh: "放鬆閒晃", level: "口語", tag: "娛樂休閒", example: "Let's just **chill** at home this Friday.", exampleZh: "這個星期五我們就在家放鬆吧。" },
  { word: "blockbuster", pos: "n.", zh: "賣座強片", level: "口語", tag: "娛樂休閒", example: "That new superhero movie is a huge **blockbuster**.", exampleZh: "那部新的超級英雄電影是超賣座強片。" },
  { word: "fan", pos: "n.", zh: "粉絲", level: "L1", tag: "娛樂休閒", example: "I'm a huge **fan** of that band.", exampleZh: "我是那個樂團的超級粉絲。" },
  { word: "plot", pos: "n.", zh: "劇情", level: "L3", tag: "娛樂休閒", example: "The movie's **plot** was confusing at first.", exampleZh: "這部電影的劇情一開始有點難懂。" },
  { word: "soundtrack", pos: "n.", zh: "電影配樂", level: "L4", tag: "娛樂休閒", example: "The movie's **soundtrack** is stuck in my head.", exampleZh: "這部電影的配樂一直在我腦中揮之不去。" },
  { word: "amusement", pos: "n.", zh: "娛樂、樂趣", level: "L3", tag: "娛樂休閒", example: "The clown was a great source of **amusement**.", exampleZh: "那個小丑帶來了很多歡樂。" },
  { word: "leisure", pos: "n.", zh: "休閒", level: "L3", tag: "娛樂休閒", example: "I spend my **leisure** time reading comics.", exampleZh: "我把休閒時間都拿來看漫畫。" },
  { word: "spoiler", pos: "n.", zh: "劇透", level: "口語", tag: "娛樂休閒", example: "Please don't give me any **spoilers**!", exampleZh: "拜託不要跟我劇透！" },
  { word: "jam session", pos: "n.", zh: "即興演奏", level: "口語", tag: "娛樂休閒", example: "The band had a **jam session** after practice.", exampleZh: "樂團在練習後即興演奏了一段。" },
  { word: "play a game", pos: "phr.", zh: "玩遊戲", level: "L1", tag: "娛樂休閒", example: "Do you want to **play a game** with us?", exampleZh: "你想跟我們一起玩遊戲嗎？" },
  { word: "get bored", pos: "phr.", zh: "感到無聊", level: "L2", tag: "娛樂休閒", example: "I **get bored** if I stay home all day.", exampleZh: "如果整天待在家我會覺得無聊。" },

  // ===== 天氣環境 Weather & Environment =====
  { word: "weather", pos: "n.", zh: "天氣", level: "L1", tag: "天氣環境", example: "The **weather** is perfect for a picnic today.", exampleZh: "今天的天氣很適合野餐。" },
  { word: "rain", pos: "v.", zh: "下雨", level: "L1", tag: "天氣環境", example: "It started to **rain** on our way home.", exampleZh: "我們回家的路上開始下雨了。" },
  { word: "sunny", pos: "adj.", zh: "晴朗的", level: "L1", tag: "天氣環境", example: "It's a **sunny** day, so let's go outside.", exampleZh: "今天天氣晴朗，我們出去走走吧。" },
  { word: "cloudy", pos: "adj.", zh: "多雲的", level: "L1", tag: "天氣環境", example: "The sky looks **cloudy** this morning.", exampleZh: "今天早上天空看起來多雲。" },
  { word: "windy", pos: "adj.", zh: "有風的", level: "L1", tag: "天氣環境", example: "It's too **windy** to fly a kite today.", exampleZh: "今天風太大了不適合放風箏。" },
  { word: "temperature", pos: "n.", zh: "溫度", level: "L2", tag: "天氣環境", example: "The **temperature** dropped a lot last night.", exampleZh: "昨晚溫度下降了很多。" },
  { word: "humid", pos: "adj.", zh: "潮濕的", level: "L3", tag: "天氣環境", example: "Summer in Taiwan is really **humid**.", exampleZh: "台灣的夏天真的很潮濕。" },
  { word: "typhoon", pos: "n.", zh: "颱風", level: "L2", tag: "天氣環境", example: "School was canceled because of the **typhoon**.", exampleZh: "因為颱風學校停課了。" },
  { word: "thunderstorm", pos: "n.", zh: "雷雨", level: "L3", tag: "天氣環境", example: "A **thunderstorm** hit the city last night.", exampleZh: "昨晚一場雷雨襲擊了這座城市。" },
  { word: "forecast", pos: "n.", zh: "預報", level: "L3", tag: "天氣環境", example: "The weather **forecast** says it will rain tomorrow.", exampleZh: "天氣預報說明天會下雨。" },
  { word: "climate", pos: "n.", zh: "氣候", level: "L3", tag: "天氣環境", example: "The island has a mild **climate** all year.", exampleZh: "這座島全年氣候都很溫和。" },
  { word: "pollution", pos: "n.", zh: "污染", level: "L3", tag: "天氣環境", example: "Air **pollution** is a big problem in the city.", exampleZh: "空氣污染是這座城市的一大問題。" },
  { word: "recycle", pos: "v.", zh: "回收", level: "L2", tag: "天氣環境", example: "We **recycle** paper and plastic bottles at home.", exampleZh: "我們在家會回收紙類和塑膠瓶。" },
  { word: "environment", pos: "n.", zh: "環境", level: "L2", tag: "天氣環境", example: "We should all try to protect the **environment**.", exampleZh: "我們都應該試著保護環境。" },
  { word: "drought", pos: "n.", zh: "乾旱", level: "L4", tag: "天氣環境", example: "The **drought** lasted for several months.", exampleZh: "這場乾旱持續了好幾個月。" },
  { word: "flood", pos: "n.", zh: "洪水", level: "L3", tag: "天氣環境", example: "Heavy rain caused a **flood** in the village.", exampleZh: "大雨造成了村莊淹水。" },
  { word: "global warming", pos: "n.", zh: "全球暖化", level: "L4", tag: "天氣環境", example: "**Global warming** is affecting the whole planet.", exampleZh: "全球暖化正影響著整個地球。" },
  { word: "greenhouse effect", pos: "n.", zh: "溫室效應", level: "L5", tag: "天氣環境", example: "The **greenhouse effect** traps heat in the atmosphere.", exampleZh: "溫室效應會把熱能困在大氣層裡。" },
  { word: "freezing", pos: "adj.", zh: "極冷的", level: "L2", tag: "天氣環境", example: "It's **freezing** outside, so wear a coat.", exampleZh: "外面冷得要命，記得穿外套。" },
  { word: "boiling", pos: "adj.", zh: "極熱的", level: "L2", tag: "天氣環境", example: "It's **boiling** hot in the classroom today.", exampleZh: "教室今天熱得要命。" },
  { word: "pour", pos: "v.", zh: "下傾盆大雨", level: "口語", tag: "天氣環境", example: "It's **pouring** outside, so bring an umbrella.", exampleZh: "外面正下著傾盆大雨，記得帶傘。" },
  { word: "muggy", pos: "adj.", zh: "悶熱的", level: "口語", tag: "天氣環境", example: "The air feels **muggy** before a storm.", exampleZh: "暴風雨來臨前空氣感覺很悶熱。" },
  { word: "clear up", pos: "phr.", zh: "天氣放晴", level: "口語", tag: "天氣環境", example: "The sky should **clear up** by the afternoon.", exampleZh: "天氣應該會在下午放晴。" },
  { word: "chilly", pos: "adj.", zh: "涼涼的", level: "L2", tag: "天氣環境", example: "It gets a bit **chilly** in the evening.", exampleZh: "晚上會變得有點涼。" },
  { word: "gloomy", pos: "adj.", zh: "陰沉的", level: "L4", tag: "天氣環境", example: "The **gloomy** sky made everyone feel sleepy.", exampleZh: "陰沉的天空讓大家都覺得昏昏欲睡。" },
  { word: "breeze", pos: "n.", zh: "微風", level: "L2", tag: "天氣環境", example: "A cool **breeze** blew through the window.", exampleZh: "一陣涼爽的微風從窗戶吹了進來。" },

  // ===== 工作未來 Work & Future =====
  { word: "job", pos: "n.", zh: "工作", level: "L1", tag: "工作未來", example: "She got a part-time **job** at a cafe.", exampleZh: "她在一間咖啡廳找到一份兼職工作。" },
  { word: "career", pos: "n.", zh: "職業生涯", level: "L3", tag: "工作未來", example: "He wants to build a **career** in medicine.", exampleZh: "他想在醫學領域發展職業生涯。" },
  { word: "interview", pos: "n.", zh: "面試", level: "L2", tag: "工作未來", example: "I have a job **interview** tomorrow morning.", exampleZh: "我明天早上有一場工作面試。" },
  { word: "resume", pos: "n.", zh: "履歷", level: "L3", tag: "工作未來", example: "She updated her **resume** before applying.", exampleZh: "她在應徵前更新了她的履歷。" },
  { word: "salary", pos: "n.", zh: "薪水", level: "L3", tag: "工作未來", example: "The new job offers a good **salary**.", exampleZh: "這份新工作提供不錯的薪水。" },
  { word: "boss", pos: "n.", zh: "老闆", level: "L2", tag: "工作未來", example: "My **boss** gave me next Monday off.", exampleZh: "我老闆讓我下週一放假。" },
  { word: "colleague", pos: "n.", zh: "同事", level: "L3", tag: "工作未來", example: "I had lunch with a **colleague** today.", exampleZh: "我今天跟一位同事一起吃午餐。" },
  { word: "internship", pos: "n.", zh: "實習", level: "L4", tag: "工作未來", example: "She did an **internship** at a design company.", exampleZh: "她在一間設計公司實習過。" },
  { word: "part-time job", pos: "n.", zh: "兼職工作", level: "L2", tag: "工作未來", example: "I have a **part-time job** at the bookstore.", exampleZh: "我在書店有一份兼職工作。" },
  { word: "full-time", pos: "adj.", zh: "全職的", level: "L3", tag: "工作未來", example: "He just started a **full-time** position.", exampleZh: "他剛開始一份全職的工作。" },
  { word: "promotion", pos: "n.", zh: "升遷", level: "L4", tag: "工作未來", example: "She got a **promotion** after two years.", exampleZh: "她工作兩年後獲得升遷。" },
  { word: "overtime", pos: "n.", zh: "加班", level: "L4", tag: "工作未來", example: "He often works **overtime** on weekdays.", exampleZh: "他平日常常加班。" },
  { word: "skill", pos: "n.", zh: "技能", level: "L2", tag: "工作未來", example: "Teamwork is an important **skill**.", exampleZh: "團隊合作是一項重要的技能。" },
  { word: "experience", pos: "n.", zh: "經驗", level: "L2", tag: "工作未來", example: "This internship gave me great **experience**.", exampleZh: "這次實習給了我很棒的經驗。" },
  { word: "goal", pos: "n.", zh: "目標", level: "L2", tag: "工作未來", example: "My **goal** is to become a teacher.", exampleZh: "我的目標是成為一名老師。" },
  { word: "ambition", pos: "n.", zh: "抱負", level: "L4", tag: "工作未來", example: "She has a lot of **ambition** for her future.", exampleZh: "她對自己的未來有很大的抱負。" },
  { word: "entrepreneur", pos: "n.", zh: "創業家", level: "L5", tag: "工作未來", example: "He dreams of becoming an **entrepreneur**.", exampleZh: "他夢想成為一名創業家。" },
  { word: "resign", pos: "v.", zh: "辭職", level: "L4", tag: "工作未來", example: "She decided to **resign** from her job.", exampleZh: "她決定辭去她的工作。" },
  { word: "workplace", pos: "n.", zh: "職場", level: "L3", tag: "工作未來", example: "A friendly **workplace** makes work more enjoyable.", exampleZh: "友善的職場讓工作更愉快。" },
  { word: "burnout", pos: "n.", zh: "職業倦怠", level: "口語", tag: "工作未來", example: "He quit because of **burnout**.", exampleZh: "他因為職業倦怠而辭職了。" },
  { word: "side hustle", pos: "n.", zh: "副業", level: "口語", tag: "工作未來", example: "She sells handmade jewelry as a **side hustle**.", exampleZh: "她把賣手工飾品當作副業。" },
  { word: "nine-to-five", pos: "n.", zh: "朝九晚五的工作", level: "口語", tag: "工作未來", example: "He's tired of his boring **nine-to-five** job.", exampleZh: "他厭倦了那份無聊朝九晚五的工作。" },
  { word: "climb the corporate ladder", pos: "phr.", zh: "在職場往上爬", level: "口語", tag: "工作未來", example: "She worked hard to **climb the corporate ladder**.", exampleZh: "她努力工作只為了在職場往上爬。" },
  { word: "work-life balance", pos: "n.", zh: "工作與生活平衡", level: "L4", tag: "工作未來", example: "It's important to have a good **work-life balance**.", exampleZh: "擁有良好的工作與生活平衡很重要。" },
  { word: "freelancer", pos: "n.", zh: "自由工作者", level: "L4", tag: "工作未來", example: "My sister works as a **freelancer** now.", exampleZh: "我姐姐現在是一名自由工作者。" },
  { word: "networking", pos: "n.", zh: "建立人脈", level: "L4", tag: "工作未來", example: "**Networking** can help you find good job opportunities.", exampleZh: "建立人脈能幫助你找到好的工作機會。" },
  { word: "qualification", pos: "n.", zh: "資格", level: "L5", tag: "工作未來", example: "You need certain **qualifications** for this job.", exampleZh: "這份工作需要特定的資格條件。" },
];

// 讓其他檔案（app.js）可以直接用全域變數 WORDS 取用這份字庫
window.WORDS = WORDS;
